# Compose file for test containers
services:
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq-container
    hostname: test-rabbit
    ports:
      - "5672:5672"
# volumes:
#   redis_data:
